name: Release Draft

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  draft:
    name: Create release draft
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
